### ISSUE TITLE
Is there a compilation guide?, I can't compile

### ISSUE THREAD

**Issue by Pakiucs151** [AudiosurfResearch/Quest3DTamperer#1]
Can there be a guide or tutorial on how to compile the program?

I am trying to compile this program, but it gives me some syntax and identifier errors related to "A3d_Channel"
I have tried using Quest3D sdk 4.0 and 5.0 but both give the same problem, i have no idea of what im doing wrong but want to make this work and unlock Audiosurf CGR files to mod the game
I must also admit that I don't know how to program yet, but im trying as hard as i can to get this working

![Doesnt Compile](https://user-images.githubusercontent.com/66497859/212812431-bbaaa56e-cdd0-4959-8038-1c51ba714def.PNG)

**Comment by RubberDuckShobe** [comment]
The headers from the Quest3D SDK are ancient, so that might be why there's
some issues with compiling them today.
I had to fix them myself, so I can probably give you the fixed header files
later today.

By the way, where did you get 5.0 from?

**Comment by Pakiucs151** [comment]
Okay, my discord profile is: Pakiucs151#4817

I would really appreciate it if you can give me the fixed headed files
I got the Quest 3D 5.0 from an old forum, i had to do a lot of research to get it, i have the full program and its SDK, i can give them to you if you want, just send me a message
