### ISSUE TITLE
Unable to compile despite no errors

### ISSUE THREAD

**Issue by Haidro6848** [AudiosurfResearch/Quest3DTamperer#3]
I have done all include and library references; for some reason, there are no errors but I'm still unable to compile. Which version of Visual Studio and C++ are you using? Any chance we could chat about this further via Discord to get it working? Thanks in advance!

**Comment by RubberDuckShobe** [comment]
What do you mean by "unable to compile"? Does it just not create a .dll file? What does the compiler output? Surely there has to be some indicator in the logs

My VS version is:

```
Microsoft Visual Studio Community 2022
Version 17.3.1
```
My platform toolset is ``Visual Studio 2022 (v143)``

**Comment by Haidro6848** [comment]
I asked about your VS version and platform toolset because the errors I'm getting are not related to your code. (see below)
They seem to be coming from the referenced libraries. Do you have any particular setup in your VS?

```
1>C:\q3dsdk\include\A3d_ChannelGroup.h(82,21): error C2433: 'A3d_ChannelGroup::A3d_Channel': 'virtual' not permitted on data declarations

1>C:\q3dsdk\include\A3d_ChannelGroup.h(82,21): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int

1>C:\q3dsdk\include\A3d_ChannelGroup.h(82,47): error C2238: unexpected token(s) preceding ';'

1>C:\q3dsdk\include\A3d_ChannelGroup.h(84,29): error C2061: syntax error: identifier 'A3d_Channel'

1>C:\q3dsdk\include\A3d_ChannelGroup.h(91,38): error C2061: syntax error: identifier 'A3d_Channel'

1>C:\q3dsdk\include\A3d_ChannelGroup.h(93,21): error C2143: syntax error: missing ';' before '*'

1>C:\q3dsdk\include\A3d_ChannelGroup.h(93,21): error C2433: 'A3d_ChannelGroup::A3d_Channel': 'virtual' not permitted on data declarations

1>C:\q3dsdk\include\A3d_ChannelGroup.h(93,21): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int

1>C:\Users\admin\Downloads\graphviz-main\lib\common\types.h(173,18): error C2061: syntax error: identifier 'GVJ_t'

1>C:\Users\admin\Downloads\graphviz-main\lib\common\types.h(283,8): error C2143: syntax error: missing ';' before '*'

1>C:\Users\admin\Downloads\graphviz-main\lib\common\types.h(283,8): error C4430: missing type specifier - int assumed. 
Note: C++ does not support default-int

1>C:\Users\admin\Downloads\graphviz-main\lib\common\types.h(283,12): error C2238: unexpected token(s) preceding ';'
```

**Comment by RubberDuckShobe** [comment]
Oh, I see. The Quest3D SDK is *crusty old* and it requires manual fixing to
make it compile. No idea what's happening with Graphviz, though. I use
Graphviz from vcpkg

I'll go send the fixed SDK in a second. This is probably something I'm not
allowed to do, but let's be honest here, the engine is old as hell and the
devs sure won't care.

**Comment by RubberDuckShobe** [comment]
[Here you go](https://github.com/AudiosurfResearch/Quest3DTamperer/files/11011987/fixed-q3dsdk-40.zip)

**Comment by Haidro6848** [comment]
Cheers, it worked! 

I'm assuming the .dll goes into the root directory of the game, where QuestViewer.exe is?

**Comment by RubberDuckShobe** [comment]
You have to inject the DLL into the running game with a DLL injector. You can make one yourself pretty easily, but using something like Cheat Engine or Process Hacker 2 should work as well.

**Comment by RubberDuckShobe** [comment]
Somehow forgot to close this lmao
