### ISSUE TITLE
Either provide binary or build instructions

### ISSUE THREAD

**Issue by GitHuhl** [AudiosurfResearch/Quest3DTamperer#4]
Is there something preventing this from just being offered ready-to-go? This project is interesting, but lacks a way to run it and instructions to build it. 

I cannot for the life of me figure out how to get this working without making a Microsoft account and downloading 30 GB of some entire IDE I'll only use once just to build this, for it to maybe work. Does anyone know if this works outside audiosurf yet? 

Provide an avenue to the community to find the answer to that question, please... Now somebody has forked the project with equally unhelpful instructions, but changing to vspkg for dependency management.. The more things change, the more they stay the same! =)

**Comment by RubberDuckShobe** [comment]
Hello, sorry for the trouble. I never imagined anyone would be interested in this repo, so the thought of offering build instructions and binaries didn't really cross my mind.

I'd go upload a binary now, but this software simply stopped working for me recently, for some reason. Uploading a binary of something that doesn't work *probably* wouldn't help.
The code was written by me with next to no prior knowledge in C/C++ and it really shows.
I intend on making a replacement for this someday, once I find the time to do so.

Therefore, I advise against using this.
If you just want to know more about the internals of the engine, I'd be more than happy to answer any of your questions to the best of my ability.
Seriously, I can't even claim that this thing Works On My Machine™ anymore.

That being said, if you really want to build this yourself, this should let you get the build tools needed without installing VS. You'll also need
Quest3D SDK header files (I'm pretty sure I used ones from 4.0). I could try posting those later.

https://github.com/Data-Oriented-House/PortableBuildTools

**Comment by GitHuhl** [comment]
Please delete your useless software repo, then.

**Comment by RubberDuckShobe** [comment]
I am not obligated to do anything for you, especially with that tone of yours.

**Comment by Razzile** [comment]
I made a fork with 64-bit fixes for a friend. maybe you'll have some luck with it. https://github.com/Razzile/Quest3DTamperer

I am not planning on maintaining it though so please don't ask for support :)
